# Generated by Django 5.2.3 on 2025-07-01 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 1, 19, 49, 46, 527590, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='post',
            name='post_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
